# Generated by Django 6.0 on 2025-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='blur_amount',
            field=models.FloatField(default=0.0, help_text='Степень размытия в пикселях (например, 0.0 - 20.0)'),
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='scale_factor',
            field=models.FloatField(default=1.0, help_text='Множитель масштаба (например, 0.5 - 2.0)'),
        ),
    ]
