# Generated by Django 6.0 on 2025-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='background_blur',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Размытие'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='background_image_url',
            field=models.URLField(blank=True, verbose_name='URL фона'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='background_opacity',
            field=models.FloatField(default=0.2, help_text='0–1', verbose_name='Прозрачность'),
        ),
    ]
