# Generated by Django 6.0 on 2025-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactinfo_background_blur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='background_blur',
            new_name='bg_blur',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='background_image_url',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='background_opacity',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='bg_image_url',
            field=models.URLField(blank=True, verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='bg_opacity',
            field=models.FloatField(default=0.2, verbose_name='Прозрачность'),
        ),
    ]
